global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'archivist'
    static_configs:
      - targets: ['web:5050']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.181.154:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100'] 